export default function Preload() {
  return (
    <>
      <link
        rel="preload"
        href="/bigelow.svg"
        as="image"
        type="image/svg+xml"
      />
      <link
        rel="preload"
        href="/fedex.svg"
        as="image"
        type="image/svg+xml"
      />
      <link
        rel="preload"
        href="/goldair.svg"
        as="image"
        type="image/svg+xml"
      />
      <link
        rel="preload"
        href="/oreilly.svg"
        as="image"
        type="image/svg+xml"
      />
    </>
  );
} 